# Base image
FROM python:3.8-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the application code
COPY . .

# Expose Flask's port
EXPOSE 5000

# Command to run the Flask app
CMD ["python", "app.py"]
