# Dockerfile.web

FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && mkdir -p /app/db && chmod -R 777 /app/db

# Copy the appy.py file from the root directory and the templates folder
COPY appy.py /app/appy.py
COPY templates/ /app/templates/

# Expose the port Flask is using
EXPOSE 5000

# Command to run the Flask app
CMD ["python3", "/app/appy.py"]
